### ISSUE TITLE
I got a question about errors

### ISSUE THREAD

**Issue by PinkyRabbit** [pastorsj/blog-api#52]
Hello! Its just a question. I dunno where to asking you so try to ask you here. I started testing my apps and have alot of questions thats why I here. I got the question. Cant understand mechanic of your errors handlers.
```javascript
// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
    app.use((err, req, res) => {
        if (err.name === 'UnauthorizedError') {
            res.status(401).send({ error: err });
        } else {
            res.status(err.status || 500);
        }
        log.critical(err);
    });
}

// production error handler
// no stacktraces leaked to user
app.use((err, req, res) => {
    if (err.name === 'UnauthorizedError') {
        res.status(401).send({ error: err });
    } else {
        res.status(err.status || 500);
    }
    log.critical(err);
});
```
There is two same structured routes. But you said that first will show errors stack, and the second - not. Why? Thanks!

**Comment by pastorsj** [comment]
@PinkyRabbit Great question, two-part answer. The reason the second is not being used is that the environment is always in development. The boilerplate for this code was generated using express-generator, which produces two error handlers. Ideally, the way you handle errors in production is different than the way you handle errors in development, but I have not made any discernable changes to make these differences. So technically, the second does nothing (for now).

**Comment by PinkyRabbit** [comment]
Oh, ok! Thanks for your response. I just had made error handler in app before with `boom`, and, when I saw your routes and comments, I thought that I missed most important thing about errors handling in express apps. Thats why I asked. :rofl:
